version: '3.7'
services:
    app:
        image: node:18
        command: bash -c "yarn install && yarn run dev"
        ports:
            - 80:3000
        working_dir: /app
        volumes:
            - ./:/app # Important: Current Host OS Dir : Sandbox OS Dir
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_DB: todos

    mysql:
        image: mysql:5.7
        volumes:
            - todo-mysql-data:/var/lib/mysql # Important: Path to Store in Host OS : Path where Stored in Sandbox OS
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: todos

volumes:
    todo-mysql-data: # Important: Named volume with default settings.
